AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-unique-bucket-name-12345  # Replace with a unique bucket name
      VersioningConfiguration:
        Status: Enabled  # Enables versioning on the bucket
      AccessControl: Private  # Controls who can access the bucket (options: Private, PublicRead, etc.)
      Tags:
        - Key: Name
          Value: MyS3Bucket
