version: 0.2

env:
  parameter-store:
    docker_user: "/docker/username"
    docker_pass: "/docker/password"

phases:
  install:
    runtime-versions:
      python: latest

  pre_build:
    commands:
      - pip install -r requirements.txt  # Fixed the spelling error

  build:
    commands:
      - echo "Git checkout completed"
      - echo "Logging into Docker Hub"
      - docker login --username $docker_user --password $docker_pass
      - echo "Successfully logged in to Docker Hub"  # Fixed the spelling error
      - echo "Building Docker image"
      - docker build --network host -t "gowtham904/new-image:$CODEBUILD_BUILD_NUMBER" .
      - docker push "gowtham904/new-image:$CODEBUILD_BUILD_NUMBER"

  post_build:
    commands:
      - echo "Image built successfully and pushed to Docker Hub"  # Fixed the spelling error

artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)  # This needs to be handled in the build phase, not in the artifacts section
